---
steps:
- name: "Build & Push -> Docker Hub"
  image: plugins/docker
  environment:
    PLUGIN_AUTO_LABEL: false
  settings:
    username: 
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    context: .
    dockerfile: Dockerfile
    repo: coralhl/woodpecker-portainer-plugin
    tags:
    - latest

- name: "Test Deploy Compose"
  image: coralhl/woodpecker-portainer-plugin
  settings: 
    portainer_instance:
      from_secret: portainer_instance
    # default name might be local or Primary
    portainer_endpoint_name: local
    portainer_username:
      from_secret: portainer_username
    portainer_password:
      from_secret: portainer_password
    # optional
    global_env:
      from_secret: compose_environment
    # optional // forces plugin to update only this compose
    docker_compose_file: ./test_files/docker-compose.yml