version: '3.3'

volumes:
  conf:
  db:

services:
  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - db:/var/lib/mysql
  
  app:
    image: fireflyiii/core:latest
    depends_on:
      - db
    volumes:
      - conf:/var/www/html/storage/upload
    environment:
      # You can leave this on "local". If you change it to production most console commands will ask for extra confirmation.
      - APP_ENV=local
      - APP_DEBUG=false # Set to true if you want to see debug information in error screens.
      - SITE_OWNER=test@gmail.com
      # The encryption key for your sessions. Keep this very secure.
      # Change it to a string of exactly 32 chars or use something like `php artisan key:generate` to generate it.
      # If you use Docker or similar, you can set this variable from a file by using APP_KEY_FILE
      - APP_KEY=byi1ZCOI2UmOx69YafK8kdXZPoR
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=equal    #Equal to DEFAULT_LANGUAGE
      - TZ=Europe/Madrid
      # TRUSTED_PROXIES is a useful variable when using Docker and/or a reverse proxy. Set it to ** and reverse proxies work just fine.
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack
      # Log level. You can set this from least severe to most severe: debug, info, notice, warning, error, critical, alert, emergency
      - APP_LOG_LEVEL=notice
      # Audit log level. Set to "emergency" if you dont want to store audit logs, leave on info otherwise.
      - AUDIT_LOG_LEVEL=info

      # Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
      # For other database types, please see the FAQ: https://docs.firefly-iii.org/support/faq
      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      # Use "pgsql" for PostgreSQL
      # Use "mysql" for MySQL and MariaDB.
      # Use "sqlite" for SQLite.
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=secret_firefly_password

      # MySQL supports SSL. You can configure it here.
      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      - MYSQL_USE_SSL=false
      - MYSQL_SSL_VERIFY_SERVER_CERT=true
      # You need to set at least of these options
      - MYSQL_SSL_CAPATH=/etc/ssl/certs/
      - MYSQL_SSL_CA=
      - MYSQL_SSL_CERT=
      - MYSQL_SSL_KEY=
      - MYSQL_SSL_CIPHER=

      # PostgreSQL supports SSL. You can configure it here.
      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      - PGSQL_SSL_MODE=prefer
      - PGSQL_SSL_ROOT_CERT=null
      - PGSQL_SSL_CERT=null
      - PGSQL_SSL_KEY=null
      - PGSQL_SSL_CRL_FILE=null

      # If you're looking for performance improvements, you could install memcached.
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file

      # If you set either of these to 'redis', you might want to update these settings too
      # If you use Docker or similar, you can set REDIS_HOST_FILE, REDIS_PASSWORD_FILE or
      # REDIS_PORT_FILE to set the value from a file instead of from an environment variable

      # can be tcp, unix or http
      - REDIS_SCHEME=tcp

      # use only when using 'unix' for REDIS_SCHEME. Leave empty otherwise.
      - REDIS_PATH=

      # use only when using 'tcp' or 'http' for REDIS_SCHEME. Leave empty otherwise.
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379

      - REDIS_PASSWORD=null
      # always use quotes and make sure redis db "0" and "1" exists. Otherwise change accordingly.
      - REDIS_DB="0"
      - REDIS_CACHE_DB="1"

      # Cookie settings. Should not be necessary to change these.
      # If you use Docker or similar, you can set COOKIE_DOMAIN_FILE to set
      # the value from a file instead of from an environment variable
      - COOKIE_PATH="/"
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
      - COOKIE_SAMESITE=lax

      # If you want Firefly III to mail you, update these settings
      # For instructions, see: https://docs.firefly-iii.org/advanced-installation/email
      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      - MAIL_MAILER=log
      - MAIL_HOST=null
      - MAIL_PORT=2525
      - MAIL_FROM=changeme@example.com
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null

      # Other mail drivers:
      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      - MAILGUN_DOMAIN=
      - MAILGUN_SECRET=


      # If you are on EU region in mailgun, use api.eu.mailgun.net, otherwise use api.mailgun.net
      # If you use Docker or similar, you can set this variable from a file by appending it with _FILE
      - MAILGUN_ENDPOINT=api.mailgun.net

      # If you use Docker or similar, you can set these variables from a file by appending them with _FILE
      - MANDRILL_SECRET=
      - SPARKPOST_SECRET=

      # Firefly III can send you the following messages
      - SEND_REGISTRATION_MAIL=true
      - SEND_ERROR_MESSAGE=true
      - SEND_LOGIN_NEW_IP_WARNING=true

      # These messages contain (sensitive) transaction information:
      - SEND_REPORT_JOURNALS=true

      # Set a Mapbox API key here (see mapbox.com) so there might be a map available at various places.
      # If you use Docker or similar, you can set this variable from a file by appending it with _FILE
      # Take note: it is no longer necessary to set this value, and it will be removed in future versions.
      - MAPBOX_API_KEY=

      #
      # Instead of the mapbox API key, just set this value to true if you want to set the location
      # of certain things, like transactions. Since this involves an external service, it's optional
      # and disabled by default.
      #
      - ENABLE_EXTERNAL_MAP=false

      # The map will default to this location:
      - MAP_DEFAULT_LAT=51.983333
      - MAP_DEFAULT_LONG=5.916667
      - MAP_DEFAULT_ZOOM=6

      # Firefly III has two options for user authentication. "eloquent" is the default,
      # and "ldap" for LDAP servers.
      # For full instructions on these settings please visit:
      # https://docs.firefly-iii.org/advanced-installation/authentication
      # If you use Docker or similar, you can set this variable from a file by appending it with _FILE
      #
      # If you enable 'ldap' AND you run Docker, the Docker image will contact packagist.org
      # This is necessary to download the required packages.
      #
      - LOGIN_PROVIDER=eloquent

      # It's also possible to change the way users are authenticated. You could use Authelia for example.
      # Authentication via the REMOTE_USER header is supported. Change the value below to "remote_user_guard".
      #
      # This will also allow Windows SSO.
      #
      # If you do this please read the documentation for instructions and warnings:
      # https://docs.firefly-iii.org/advanced-installation/authentication
      #
      # This function is available in Firefly III v5.3.0 and higher.
      - AUTHENTICATION_GUARD=web

      # If the guard is changed, Firefly III uses the 'REMOTE_USER' header as per RFC 3875.
      # You can also use another header, like AUTH_USER when using Windows SSO.
      # Some systems use X-Auth headers. In that case, use HTTP_X_AUTH_USERNAME or HTTP_X_AUTH_EMAIL
      # Depending on your system, REMOTE_USER may need to be changed to HTTP_REMOTE_USER
      #
      # If this header is 'unexpectedly empty', check out the documentation.
      # https://docs.firefly-iii.org/advanced-installation/authentication
      #
      - AUTHENTICATION_GUARD_HEADER=REMOTE_USER

      #
      # Firefly III uses email addresses as user identifiers. When you're using an external authentication guard
      # that doesn't do this, Firefly III is incapable of emailing you. Messages sent to "Bill Gates" always fail.
      #
      # However, if you set this value, Firefly III will store the value from this header as the user's backup
      # email address and use it to communicate. So user "Bill Gates" could still have
      # the email address "bill@microsoft.com".
      #
      # Example value: AUTHENTICATION_GUARD_EMAIL=HTTP_X_AUTH_EMAIL
      #
      - AUTHENTICATION_GUARD_EMAIL=


      # It's impossible to log out users who's authentication is handled by an external system.
      # Enter a custom URL here that will force a logout (your authentication provider can tell you).
      # Setting this variable only works when AUTHENTICATION_GUARD != web
      #
      - CUSTOM_LOGOUT_URI=

      # LDAP connection configuration
      # OpenLDAP, FreeIPA or ActiveDirectory
      # # If you use Docker or similar, you can set this variable from a file by appending it with _FILE
      - ADLDAP_CONNECTION_SCHEME=OpenLDAP
      - ADLDAP_AUTO_CONNECT=true

      # LDAP connection settings
      # You can set the following variables from a file by appending them with _FILE:
      # ADLDAP_CONTROLLERS, ADLDAP_PORT, ADLDAP_BASEDN
      - ADLDAP_CONTROLLERS=
      - ADLDAP_PORT=389
      - ADLDAP_TIMEOUT=5
      - ADLDAP_BASEDN=""
      - ADLDAP_FOLLOW_REFFERALS=false